name: Backend CD Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: backend-cd-dev
  cancel-in-progress: true

jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    env:
      ECS_CLUSTER_NAME: dev # 배포하고자 하는 cluster 명
      ECS_CONTAINER_NAME: fastapi # ecs -> 태스크정의 내의 컨테이너 이름
      ECS_SERVICE_NAME: llm-economy-service # ecs에서 사용하는 서비스명
      TASK_DEFINITION_NAME: llm-economy-task # ecs -> 태스크 정의 명
    outputs:
      imageRepository: ${{ steps.image.outputs.repository }}
      imageTag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2
          mask-aws-account-id: no

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set tag
        id: tag
        run: |
          TAG=$(echo ${{ github.sha }} | cut -c1-8)
          echo TAG=$TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set image.repository
        id: image
        run: |
          echo "repository=${{ steps.login-ecr.outputs.registry }}/llm-economy/backend" >> $GITHUB_OUTPUT

      - name: Build and push image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.repository }}:${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download Task Definition Template
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.TASK_DEFINITION_NAME }} \
            --query taskDefinition \
            > task-definition.json

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ steps.image.outputs.repository }}:${{ steps.tag.outputs.tag }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
